version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Enabled by default
    - errcheck # Check for unchecked errors
    - govet # Vet examines Go source code
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced Go linter
    - unused # Check for unused constants, variables, functions and types

    # Complexity and maintainability
    - gocyclo # Cyclomatic complexity
    - gocognit # Cognitive complexity
    - nestif # Reports deeply nested if statements

    # Bugs and correctness
    - bodyclose # Check HTTP response body is closed
    - noctx # Finds HTTP requests without context.Context
    - rowserrcheck # Check whether Rows.Err is checked
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed
    - gosec # Security issues

    # Performance
    - prealloc # Find slice declarations that could potentially be preallocated

    # Error handling
    - errname # Check error naming conventions
    - errorlint # Find code that will cause problems with Go 1.13 error wrapping
    - wrapcheck # Check that errors from external packages are wrapped

    # Code organization
    - gomodguard # Check for blocked dependencies

    # Formatting and style
    - whitespace # Check for unnecessary whitespace
    - unconvert # Remove unnecessary type conversions
    - unparam # Reports unused function parameters
    - wastedassign # Find wasted assignment statements

    # Naming conventions
    - predeclared # Find code that shadows predeclared identifiers
    - varnamelen # Check variable name length

    # Comments and documentation
    - godot # Check if comments end in a period
    - misspell # Finds commonly misspelled English words
